name: Java CI  # Nom du workflow

on:
  push:
    branches: [ main ]  # Déclenche le workflow à chaque push sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Exécute sur une machine virtuelle Ubuntu

    steps:
      - uses: actions/checkout@v3  # Étape 1: Checkout du code
      - name: Setup Java
        uses: actions/setup-java@v3  # Étape 2: Installation de Java
        with:
          java-version: '17'  # Version 17 de Java
          distribution: ''
      - name: Build with Maven
        run: mvn install  # Étape 3: Exécution de Maven